project:
  type: website
  output-dir: _site  # change to 'docs' if deploying to GitHub Pages

website:
  title: "Nguyễn Nhung"
  description: "Data • Visualization • R"
  favicon: images/favicon.png
  navbar:
    background: dark
    pinned: true
    left:
      - href: home.qmd
        text: TICKET PAKH TỒN
      - href: blog.qmd
        text: TICKET PAKH PHÁT SINH TRONG THÁNG
  page-footer:
    left: "© {2025} Nguyễn Thị Trang Nhung"
    right: "Data Analyst"

format:
  html:
    embed-resources: true    # ← nhúng toàn bộ JS/CSS vào HTML
    self-contained: true
    theme: cosmo
    toc: true
    include-after-body:
      - text: |
          <script>
            const CHECK_INTERVAL = 60000; // kiểm tra mỗi 60 giây
            
            async function getLastBuild() {
              const res = await fetch('/last-build.json?t=' + Date.now());
              const data = await res.json();
              return data.buildTime;
            }

            (async () => {
              const initialBuild = await getLastBuild();
              
              setInterval(async () => {
                const currentBuild = await getLastBuild();
                if (currentBuild !== initialBuild) {
                  window.location.reload();
                }
              }, CHECK_INTERVAL);
            })();
          </script>
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true