---
title: "Báo cáo phòng Triển khai"
format:
  html:
    page-layout: full
css: styles.css
date: '`r format(Sys.Date(), "%d/%m/%Y")`'
---

<style type="text/css">
  body{
  font-size: 13pt;
  font-family: Serif
}
</style>

<style type="text/css">
.main-container {
  max-width: 80% !important;
  margin: auto;
}
</style>

```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
#library(plyr)
library(dplyr)
library(ggplot2)
library(repr)
library(dplyr)
library(DT)
library(highcharter)
library(shiny)
#library(shinydashboard)
library(tidyr)
library(stringr)
library(dplyr)
library(tidyverse)
library(crosstalk)
library(reactable)
library(stringi)
library(raster)
#library(rgdal)
library(ggthemes)
library(ggiraph)
library(googlesheets4)
library(shinydashboard)
library(shinyWidgets)
```

```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
sheet_url <- "https://docs.google.com/spreadsheets/d/12BlvL_Fxdubk5PL4G-pjX-c4_iQwiubVlknHCrAw5dw/edit?gid=904243310#gid=904243310"
b2c_aio <- read_sheet(sheet_url, sheet = "Chi tiết")

b2c_aio <- b2c_aio[-c(1:4),c(1,2,3,10:20,22:27, 29:34, 36:44, 48, 52, 53, 55:67,51)]
n_aio <- c("don_huy", "ma_tinh", "ma_hd", "gtri", "namthang_ky", "ngay_ky", "dich_vu", "thang_DT", "ngay_tam_ung", "gtri_tam_ung", "loai_pin", "ma_pin", "ten_pin", "so_pin", "ngay_cap_pin", "dambao_pin", "loai_inver", "ma_inver", "ten_inver", "so_inver", "ngay_cap_inver", "dambao_inver", "loai_acquy", "ma_acquy", "ten_acquy", "so_acquy", "ngay_cap_acquy", "dambao_acquy", "du_hang", "du_dk", "so_hd", "tyle_tamung", "am", "han_thicong", "so_ngau_tamung", "thang_dk_DT", "mat_bang", "quahan_thicong", "BG_VHKT", "tien_do", "ngay_thicong_xong", "ngay_BBNT", "vuong", "vuong_chitiet", "do_chacchan_VHKT", "ngay_dien_thicong", "ngay_BG_sang", "thang_ky", "nam_ky", "today_ngayBG", "today_ngaythicong", "chac_chan")
colnames(b2c_aio) <- n_aio

#Chuyển các cột list định dạng giống ngày về date %m-%Y
b2c_aio1 <- b2c_aio
b2c_aio1 <- b2c_aio1 %>%
  rowwise() %>%
  mutate(namthang_ky = toString(unlist(namthang_ky))) %>%
  mutate(thang_dk_DT = toString(unlist(thang_dk_DT))) %>%
  ungroup()

b2c_aio1 <- b2c_aio1 %>%
  mutate(
    namthang_ky = ifelse(
      is.na(namthang_ky),
      NA_character_,
      format(
        as.Date(namthang_ky, format = "%Y-%m-%d"),
        format = "%m-%Y"
      )
    )
  ) %>%
  mutate(
    thang_dk_DT = ifelse(
      is.na(thang_dk_DT),
      NA_character_,
      format(
        as.Date(thang_dk_DT, format = "%Y-%m-%d"),
        format = "%m-%Y"
      )
    )
  )


####Chuyển tất cả các cột list về number
b2c_aio1[] <- b2c_aio1 %>%
  mutate(across(where(is.list), ~ {
    lens <- lengths(.)
    max_len <- max(lens)
    lapply(., function(x) {
      if(length(x) < max_len) c(unlist(x), rep(NA, max_len - length(x))) else unlist(x)
    })
  })) %>%
  mutate(across(where(is.list), unlist))

```

```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
b2c_aio1 %>% drop_na(ma_hd) -> b2c_aio1
thang_n <- format(as.Date(today(), format = , format = "%Y-%m-%d"), format = "%m-%Y")
thang_n1 <- format(as.Date(Sys.Date() %m+% months(1), format = , format = "%Y-%m-%d"), format = "%m-%Y")
thang_n2 <- format(as.Date(Sys.Date() %m+% months(2), format = , format = "%Y-%m-%d"), format = "%m-%Y")
```

## <span style="color: #C35817;font-family: cambria;">**II. DỰ KIẾN DOANH THU THÁNG ** <strong>`r thang_n`</strong></span>
### <span style="color: #C35817;font-family: cambria;">**1. Chi tiết theo tỉnh tiến độ HĐ dự kiến lên DT tháng ** <strong>`r thang_n`</strong></span>

```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  group_by(ma_tinh, am) %>%
  summarise(gtri_dk = sum(gtri[!is.na(ma_hd)], na.rm = TRUE)/10^6,
            gtri_dt = round(sum(gtri[!is.na(ma_hd) & !is.na(thang_DT)], na.rm = TRUE)/10^6,0),
            ty_le = gtri_dt*100/gtri_dk) -> bc_dk_dt

```


```{r,out.width = '120%',fig.width=7, fig.height=4, echo = FALSE, warning=FALSE, message=FALSE}
highchart() %>% 
  hc_chart(type = "column") %>%
  hc_xAxis(categories = bc_dk_dt$ma_tinh, labels = list(style=list(fontSize = "12px",fontFamily = "cambria"))) %>%
  hc_title(text = "Tỷ lệ dự kiến doanh thu tháng hiện tại",
           margin = 20, 
           align = "center",
           style = list(color = "black", fontWeight = "bold",fontFamily = "cambria",fontSize = "20px")
           ) %>% 
  hc_yAxis_multiples(list(lineWidth = 3, 
                          title = list(text = "Dự kiến DT", style=list(fontWeight = "bold",fontSize = "15px",fontFamily = "cambria")), 
                          labels = list(style=list(fontSize = "12px",fontFamily = "cambria"))),
                     list(showLastLabel = TRUE, opposite = TRUE, 
                          title = list(text = "%HT", style=list(fontWeight = "bold",fontSize = "15px",fontFamily = "cambria")), 
                          labels = list(style=list(fontSize = "12px",fontFamily = "cambria")))) %>%
  hc_add_series(name = "Tổng DT dự kiến", data = round(bc_dk_dt$gtri_dk,0),
                tooltip = list(columnFormat = paste0("Dự kiến", "\n",accounting(bc_dk_dt$gtri_hd, big.mark = ",", digits = 2L, format = "d"), "TTQH"))) %>%
  hc_add_series(name = "Đã lên DT",data = round(bc_dk_dt$gtri_dt,0)) %>%
  hc_add_series(name = "Tỷ lệ (%)",data = round(bc_dk_dt$ty_le,0), type = "spline", yAxis = 1,dataLabels = list(enabled = TRUE, format = "{y}%")) %>%
  hc_tooltip(headerFormat = "<b>{point.key}</b><br>",
             pointFormat = "{series.name}: {point.y}") %>%
  hc_colors(c("#D9D9D9", "#C84309","#645889")) %>%
  hc_legend(labels = list(style = list(color = "black", fontWeight = "bold",fontFamily = "cambria",fontSize = "20px"))) %>%
  hc_exporting(
    enabled = TRUE,
    filename = "custom-file-name"
    ) 

```


```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  group_by(ma_tinh, am) %>%
  summarise(so_dk = sum(!is.na(ma_hd)),
            gtri_dk = sum(gtri[!is.na(ma_hd)], na.rm = TRUE)/10^6,
            so_dt = sum(!is.na(ma_hd) & !is.na(thang_DT), na.rm = TRUE),
            gtri_dt = round(sum(gtri[!is.na(ma_hd) & !is.na(thang_DT)], na.rm = TRUE)/10^6,0),
            so_chua_dt = sum(!is.na(ma_hd) & is.na(thang_DT), na.rm = TRUE),
            gtri_chua_dt = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT)], na.rm = TRUE)/10^6,0),
            so_chua_dt_chac = sum(!is.na(ma_hd) & is.na(thang_DT) & chac_chan == "Chắc chắn", na.rm = TRUE),
            gtri_chua_dt_chac = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & chac_chan == "Chắc chắn"], na.rm = TRUE)/10^6,0),
            so_chua_dt_50 = so_chua_dt - so_chua_dt_chac,
            gtri_chua_dt_50 = gtri_chua_dt - gtri_chua_dt_chac) -> bc_dkdt_n

```


```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
kq1x <- unlist(bc_dkdt_n[1])
kq2x <- unlist(bc_dkdt_n[2])
kq3x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),3]), digits = 2L, format = "d", big.mark = ",")
kq4x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),4]), digits = 2L, format = "d", big.mark = ",")
kq5x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),5]), digits = 2L, format = "d", big.mark = ",")
kq6x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),6]), digits = 2L, format = "d", big.mark = ",")
kq7x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),7]), digits = 2L, format = "d", big.mark = ",")
kq8x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),8]), digits = 2L, format = "d", big.mark = ",")
kq9x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),9]), digits = 2L, format = "d", big.mark = ",")
kq10x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),10]), digits = 2L, format = "d", big.mark = ",")
kq11x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),11]), digits = 2L, format = "d", big.mark = ",")
kq12x <- accounting(unlist(bc_dkdt_n[c(1:nrow(bc_dkdt_n)),12]), digits = 2L, format = "d", big.mark = ",")

bc_dkdt_n_tb <- data.frame(kq1x,kq2x, kq3x, kq4x,kq5x,kq6x,kq7x,kq8x,kq9x, kq10x,kq11x,kq12x)
bc_dkdt_n_tb[3:12] <- lapply(bc_dkdt_n_tb[3:12], as.numeric)
rownames(bc_dkdt_n_tb) <- NULL
```

```{r,out.width = '150%', echo = FALSE, warning=FALSE, message=FALSE}
library(crosstalk)
library(reactable)
shared_bc_dkdt_n_tb <- SharedData$new(bc_dkdt_n_tb)

shiny::fluidRow(
  shiny::column(
    9,
    reactable(shared_bc_dkdt_n_tb, minRows = 3,width = 1250, height = "auto", pagination = FALSE, groupBy = "kq2x", 
              columnGroups = list(
    colGroup(paste0("Tổng DK DT T", thang_n), columns = c("kq3x", "kq4x"), sticky = "left", headerStyle = list(color = "white", background = "#F56222", whiteSpace = "normal",textAlign = "center")),
    colGroup("Đã lên DT", columns = c("kq5x", "kq6x"), sticky = "left", headerStyle = list(color = "white", background = "#009900", whiteSpace = "normal",textAlign = "center")),
    colGroup("Chưa lên DT", columns = c("kq7x", "kq8x"), sticky = "left", headerStyle = list(color = "white", background = "#3333CC", whiteSpace = "normal",textAlign = "center")),
    colGroup("Chắc chắn", columns = c( "kq9x", "kq10x"), sticky = "left", headerStyle = list(color = "white", background = "#F56222", whiteSpace = "normal",textAlign = "center")),
    colGroup("50/50", columns = c("kq11x", "kq12x"), sticky = "left", headerStyle = list(color = "white", background = "#F56222", whiteSpace = "normal",textAlign = "center"))
  ),
  resizable = TRUE,
  wrap = FALSE,
  searchable = TRUE,
  bordered = TRUE, highlight = TRUE, style = list(fontSize = "16px"),
  rowStyle = JS("
    function(rowInfo, state) {
      // Kiểm tra có subRows không → group row
      if (rowInfo.subRows && rowInfo.subRows.length > 0) {
        return {
          backgroundColor: '#FFFFFF',  // group row: trắng
          fontWeight: 'bold',
          color: '#000000',
          borderLeft: '2px solid transparent'
        };
      } else {
        return {
          borderLeft: '2px solid #ffa62d',
          backgroundColor: '#f5f5f5'   // subrows: xám nhạt
        };
      }
    }
  "), 
  theme = reactableTheme(header = "background-color: #F56222;",),
  defaultColDef = colDef(
    #headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
    footerStyle = list(fontWeight = "bold", color = "#B22222")
  ),
  defaultSorted = c("kq1x","kq2x"),
  striped = FALSE,
  columns = list(
    
    kq1x = colDef(name = "Mã tỉnh", headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
                 aggregate = JS("
        function(values, rows) {
          return values.join(', ')
        }
      "),
      aggregated = JS("
        function(cellInfo) {
          return React.createElement('span', {
            title: cellInfo.value,
            style: {cursor: 'help', fontWeight: 'bold'},
          }, cellInfo.value);
        }
      "),
      # Visual feedback khi hover
      style  = JS("
    function(rowInfo, state) {
      // Kiểm tra có subRows không → group row
      if (rowInfo.subRows && rowInfo.subRows.length > 0) {
        return {
          cursor: 'help',  // group row: trắng
          fontWeight: 'bold',
          backgroundColor: '#f5f5f5',
          textDecoration: 'underline dotted'
        };
      } else {
        return {
          backgroundColor: '#f5f5f5'   // subrows: xám nhạt
        };
      }
    }
  "),
     align = "left", width = 100, footer = "Tổng"),
    kq2x = colDef(name = "AM", headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
                  cell = JS("
        function(cellInfo) {
          // Add a tooltip to the grouped row header
          return '<span title=\"Group ' + cellInfo.value + '\">' + cellInfo.value + '</span>'
        }
      "),
      html = TRUE,
      aggregate = "count", align = "left", width = 150),
    kq3x = colDef(name = "Số lượng", headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 90, footer = function(values) sprintf("%.0f", sum(values))),
    
    kq4x = colDef(name = "Giá trị", headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 100, format = colFormat(digits = 0, separators = TRUE), footer = function(values) sprintf("%s", format(sum(values), big.mark = ",", digits = 2L))),
    
    kq5x = colDef(name = "Số lượng", headerStyle = list(color = "black", background = "#C8E2B1", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 90, footer = function(values) sprintf("%.0f", sum(values))),
    
    kq6x = colDef(name = "Giá trị", headerStyle = list(color = "black", background = "#C8E2B1", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 100, format = colFormat(digits = 0, separators = TRUE), footer = function(values) sprintf("%s", format(sum(values), big.mark = ",", digits = 2L))),
    
    kq7x = colDef(name = "Số lượng", headerStyle = list(color = "black", background = "#BFCAE6", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 90, footer = function(values) sprintf("%.0f", sum(values))),
    
    kq8x = colDef(name = "Giá trị", headerStyle = list(color = "black", background = "#BFCAE6", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 100, format = colFormat(digits = 0, separators = TRUE), footer = function(values) sprintf("%s", format(sum(values), big.mark = ",", digits = 2L))),
    
    kq9x = colDef(name = "Số lượng",headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 90, footer = function(values) sprintf("%.0f", sum(values))),
    
    kq10x = colDef(name = "Giá trị",headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 100, format = colFormat(digits = 0, separators = TRUE), footer = function(values) sprintf("%s", format(sum(values), big.mark = ",", digits = 2L))),
    
    kq11x = colDef(name = "Số lượng",headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 100, footer = function(values) sprintf("%.0f", sum(values))),
    
    kq12x = colDef(name = "Giá trị",headerStyle = list(color = "black", background = "#F5DEB3", whiteSpace = "normal",textAlign = "center"),
      aggregate = "sum", align = "right", width = 100, format = colFormat(digits = 0, separators = TRUE), footer = function(values) sprintf("%s", format(sum(values), big.mark = ",", digits = 2L)))

  )
)))
```

<span style="color: #3333CC;font-family: cambria;">**_* Di chuột qua cột Mã tỉnh để xem list tỉnh_**</span>

### <span style="color: #C35817;font-family: cambria;">**2. Tiến độ thi công HĐ dự kiến lên DT tháng ** <strong>`r thang_n`</strong></span>
```{r, warning=FALSE, message=FALSE, results = 'hide', echo = FALSE}
b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd)),
            gtri_hd = sum(gtri[!is.na(ma_hd)], na.rm = TRUE)/10^6,
            chi_tieu = paste0("Tổng dự kiến T", thang_n)
            ) -> xbc_bangiao1

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & !is.na(thang_DT), na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & !is.na(thang_DT)], na.rm = TRUE)/10^6,0),
            chi_tieu = "Đã lên DT"
            ) -> xbc_bangiao2

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT), na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT)], na.rm = TRUE)/10^6,0),
            chi_tieu = "Chưa lên DT"
            ) -> xbc_bangiao3

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Chưa bàn giao VHKT"
            ) -> xbc_bangiao4

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & dich_vu == "Thương mại", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG"  & dich_vu == "Thương mại"], na.rm = TRUE)/10^6,0),
            chi_tieu = "HĐ thương mại tự điều hành"
            ) -> xbc_bangiao5

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & so_ngau_tamung != "Đã tạm ứng đủ" & dich_vu == "Dịch vụ", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & so_ngau_tamung != "Đã tạm ứng đủ"  & dich_vu == "Dịch vụ"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Chưa tạm ứng đủ 20%"
            ) -> xbc_bangiao6

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & so_ngau_tamung == "Đã tạm ứng đủ" & du_hang == "Chưa đặt đủ hàng"  & dich_vu == "Dịch vụ", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & so_ngau_tamung == "Đã tạm ứng đủ"  & du_hang == "Chưa đặt đủ hàng" & dich_vu == "Dịch vụ"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Chưa đặt đủ hàng"
            ) -> xbc_bangiao7

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & so_ngau_tamung == "Đã tạm ứng đủ" & du_hang == "NCC chưa giao" & dich_vu == "Dịch vụ", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & so_ngau_tamung == "Đã tạm ứng đủ"  & du_hang == "NCC chưa giao" & dich_vu == "Dịch vụ"], na.rm = TRUE)/10^6,0),
            chi_tieu = "NCC chưa giao hàng"
            ) -> xbc_bangiao8

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & mat_bang == "Chưa có MB" & dich_vu == "Dịch vụ", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Chưa BG" & mat_bang == "Chưa có MB" & dich_vu == "Dịch vụ"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Chưa có mặt bằng"
            ) -> xbc_bangiao9

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Đã bàn giao VHKT"
            ) -> xbc_bangiao10

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "Chưa thi công", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "Chưa thi công"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Chưa thi công"
            ) -> xbc_bangiao11

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "Đang thi công", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "Đang thi công"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Đang thi công"
            ) -> xbc_bangiao12

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "Thi công xong", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "Thi công xong"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Thi công xong"
            ) -> xbc_bangiao13

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & ngay_BBNT != "x", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & ngay_BBNT != "x"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Đã có BBNT"
            ) -> xbc_bangiao13

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "VHKT chưa confirm", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & tien_do == "VHKT chưa confirm"], na.rm = TRUE)/10^6,0),
            chi_tieu = "VHKT chưa confirm"
            ) -> xbc_bangiao14

b2c_aio1 %>%
  filter(thang_dk_DT == thang_n) %>%
  summarise(so_hd = sum(!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & vuong != "x", na.rm = TRUE),
            gtri_hd = round(sum(gtri[!is.na(ma_hd) & is.na(thang_DT) & BG_VHKT == "Đã BG" & vuong != "x"], na.rm = TRUE)/10^6,0),
            chi_tieu = "Vướng"
            ) -> xbc_bangiao15

xbc_bangiao_full <- rbind(xbc_bangiao1, xbc_bangiao2, xbc_bangiao3, xbc_bangiao4, xbc_bangiao5, xbc_bangiao6, xbc_bangiao7, xbc_bangiao8, xbc_bangiao9, xbc_bangiao10, xbc_bangiao11, xbc_bangiao12, xbc_bangiao13, xbc_bangiao14, xbc_bangiao15)

xbc_bangiao_full <- xbc_bangiao_full %>%
  mutate(STT = c("", "I", "II", "1", "1.1", "1.2", "1.3", "1.4", "1.5", "2", "2.1", "2.2", "2.3", "2.4", "2.5"))

xbc_bangiao_full <- xbc_bangiao_full[c(4,3,1,2)]
```

```{r,out.width = '150%', echo = FALSE, warning=FALSE, message=FALSE}
library(crosstalk)
library(reactable)
shared_xbc_bangiao_full <- SharedData$new(xbc_bangiao_full)

shiny::fluidRow(
  shiny::column(
    9,
    reactable(shared_xbc_bangiao_full, minRows = 3,width = 455, height = "auto", pagination = FALSE,
  resizable = TRUE,
  wrap = FALSE,
  bordered = TRUE, highlight = TRUE, style = list(fontSize = "16px"),
  theme = reactableTheme(header = "background-color: #F56222;"),
  defaultColDef = colDef(
    headerStyle = list(color = "white", background = "#F56222", whiteSpace = "normal",textAlign = "center"),
  ),
  striped = FALSE,
  
  rowStyle = function(index) {
    if (index %in% c(2,3)) {  # index bắt đầu từ 0: hàng 2=1, 3=2, 5=4
      list(
        backgroundColor = "#FFD39B",  # nền xanh nhạt
        fontWeight = "bold",          # chữ đậm
        color = "#000"                # chữ đen
      )
    } else if (index == 1) {  # index bắt đầu từ 0: hàng 2=1, 3=2, 5=4
      list(
        backgroundColor = "#FFFF00",  # nền xanh nhạt
        fontWeight = "bold",          # chữ đậm
        color = "#EE2C2C"                # chữ đen
      )
    } else if (index %in% c(4, 10)) {  # index bắt đầu từ 0: hàng 2=1, 3=2, 5=4
      list(
        backgroundColor = "#FDE2CA",  # nền xanh nhạt
        fontWeight = "bold",          # chữ đậm
        color = "#EE2C2C"                # chữ đen
      )
    }
  },
  columns = list(
    
    STT = colDef(name = "STT", 
      aggregate = "unique", align = "left", width = 50),
    chi_tieu = colDef(name = "Chỉ tiêu",
      aggregate = "count", align = "left", width = 220),
    so_hd = colDef(name = "Số HĐ",
      aggregate = "sum", align = "right", width = 80),
    
    gtri_hd = colDef(name = "Giá trị",
      aggregate = "sum", align = "right", width = 100, format = colFormat(digits = 0, separators = TRUE))

  )
)))
```

<div style="display:flex; gap:4px; align-items:stretch;">

<div style="flex: 0 0 50%; padding: 0px;">


```{r,out.width = '150%',fig.width=4, fig.height=4, echo = FALSE, warning=FALSE, message=FALSE}
xpie_chuaBG <- xbc_bangiao_full[c(5:9), c(2,3)]
xpie_chuaBG <- xpie_chuaBG %>%
  mutate(ty_le = scales::percent(so_hd/sum(so_hd)))

hchart(
  xpie_chuaBG, "pie", hcaes(name = chi_tieu, y = so_hd),
  name = "Corte",
  innerSize = "70%",
  dataLabels = list(format = "{point.name}<br>({point.ty_le})", style = list(fontFamily = "cambria"))
) %>%
  hc_title(text = "CƠ CẤU NGUYÊN NHÂN CHƯA BÀN GIAO VHKT",
           margin = 20, 
           align = "center",
           style = list(color = "black", fontWeight = "bold",fontFamily = "cambria",fontSize = "20px")
           ) %>% 
  hc_tooltip(
    useHTML = TRUE,
    style = list(fontSize = "20px",fontFamily = "cambria"),
    headerFormat = "",
    pointFormat = "<div style='text-align: center;'> <b>{point.name}</b><br>{point.y} <br>{point.ty_le} </div>",
    positioner = JS(
      "function () {

        /* one of the most important parts! */
        xp =  this.chart.chartWidth/2 - this.label.width/2
        yp =  this.chart.chartHeight/2 - this.label.height/2

        return { x: xp, y: yp };

      }"
    ),
    shadow = FALSE,
    borderWidth = 0,
    backgroundColor = "transparent",
    hideDelay = 1000
  )

```


</div>

<div style="flex: 0 0 50%; padding: 0px;">


```{r,out.width = '100%',fig.width=4, fig.height=4, echo = FALSE, warning=FALSE, message=FALSE}
xpie_daBG <- xbc_bangiao_full[c(11:15), c(2,3)]
xpie_daBG <- xpie_daBG %>%
  mutate(ty_le = scales::percent(so_hd/sum(so_hd)))

hchart(
  xpie_daBG, "pie", hcaes(name = chi_tieu, y = so_hd),
  name = "Corte",
  innerSize = "70%",
  dataLabels = list(format = "{point.name}<br>({point.ty_le})", style = list(fontFamily = "cambria"))
) %>%
  hc_title(text = "CƠ CẤU TIẾN ĐỘ THI CÔNG",
           margin = 20, 
           align = "center",
           style = list(color = "black", fontWeight = "bold",fontFamily = "cambria",fontSize = "20px")
           ) %>% 
  hc_tooltip(
    useHTML = TRUE,
    style = list(fontSize = "20px",fontFamily = "cambria"),
    headerFormat = "",
    pointFormat = "<div style='text-align: center;'> <b>{point.name}</b><br>{point.y} <br>{point.ty_le} </div>",
    positioner = JS(
      "function () {

        /* one of the most important parts! */
        xp =  this.chart.chartWidth/2 - this.label.width/2
        yp =  this.chart.chartHeight/2 - this.label.height/2

        return { x: xp, y: yp };

      }"
    ),
    shadow = FALSE,
    borderWidth = 0,
    backgroundColor = "transparent",
    hideDelay = 1000
  )
```

</div>
</div>













